### ISSUE TITLE
Supports common datasets

### ISSUE THREAD

**Issue by felixbur** [felixbur/nkululeko#22]
Supports common datasets and new datasets at a minimum: how to convert user's dataset or common speech datasets into CSV or audformat that matches nkululeko (currently only emodb works out the box). Suggested (I have seen some in the example): ravdess, IEMOCAP, msp-improv, msp-podcast, aesdd, CaFe, Crema-D, emovo, savee, emofilm, etc. This can be achieved by providing preprocessing.py for each dataset.

**Comment by felixbur** [comment]
super, didn't know about this database project, just what is needed!
what is SSL models?

**Comment by felixbur** [comment]
Tried the strongai emotion import with Emodb (which i know best ;) but didn't work out of the box.
I guess i would start with
https://www.kaggle.com/code/shivamburnwal/speech-emotion-recognition
for simple scipts to generate the csv format
file,emotion,speaker,gender,age

**Comment by felixbur** [comment]
i started here: https://github.com/felixbur/nkululeko/tree/main/data/ravdess

**Comment by bagustris** [comment]
> super, didn't know about this database project, just what is needed! what is SSL models?

SSL --> self-supervised learning, large models like Unispeech-SAT, HuBERT, and similar.

For small datasets (maybe under 5000 samples according to the Deep Learning book), like ravdess (1440 samples), I think it is better to make cross-validations instead of a fixed split. The results will be more robust. I make 10-fold in my previous study [1], but I think 5-fold is enough.

The easiest way may be to create each CSV for each fold, but adding one more column ('fold') will make it compact to have a single CSV file.

https://github.com/felixbur/nkululeko/blob/5beddfab50edec916a200632c8af8a97d72b2e6d/data/ravdess/process_database.py#L60-L64

In the case of a single CSV file, the format will be
```
file,emotion,speaker,gender,split
```

Where `split` is from 1 to 5. For five CSV, the current version can be regarded as `ravdess_fold1.csv`.

[1] B. T. Atmaja and M. Akagi, “On The Differences Between Song and Speech Emotion Recognition: Effect of Feature Sets, Feature Types, and Classifiers,” in 2020 IEEE REGION 10 CONFERENCE (TENCON), 2020, pp. 968–972.

**Comment by felixbur** [comment]
interesting about adding fold information to the sample format, but, i think we can have both.
We do have for most databases predefined splits, of course it does not make sense to use them if the database is small (like all acted ones), but it can make sense if you agglomorate them to a large train/dev/test sets

**Comment by felixbur** [comment]
today is actually the nkululeko live workshop in southafrica and  google meet, but not sure it it's public

**Comment by bagustris** [comment]
Reference for training/dev/test split for Crema-D dataset, 

- https://www.tensorflow.org/datasets/catalog/crema_d
- https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/audio/crema_d.py

**Comment by felixbur** [comment]
i think we should close this for now, there are so many other issues open
