### ISSUE TITLE
Support path with quotes

### ISSUE THREAD

**Issue by bagustris** [felixbur/nkululeko#77]
Current behavior yield to error when we define path with quotes, e.g., 

```
data = './data/androids/androids.csv'
data.audio_path = '.'
```
Results:  
```
FileNotFoundError: [Errno 2] No such file or directory: "./'./data/androids/androids.csv'"
FileNotFoundError: [Errno 2] No such file or directory: "././data/androids/'.'/./Androids-Corpus/Interview-Task/audio/HC/01_CF56_1.wav"
```

I think the path should be able to handle string inside quotes. The motivation of using quotes is to enable code/path completion to prevent typos on typing the path. I suspect that this error is caused by the literal addition of the path using `+` instead of using `os.path.join()`.

**Comment by felixbur** [comment]
i think the  error is because we use the string literally, and do not interprete it as a string. 
of course we could simply remove any quotes that might be around strings.
Easily done
actually pathes in nkululeko often look weird because they are the outcome of several concatenations of subpathes, i guess being more careful here, and perhaps doing it properly in the first place, wouldn't hurt

**Comment by felixbur** [comment]
done
