### ISSUE TITLE
make pip install smaller

### ISSUE THREAD

**Issue by felixbur** [felixbur/nkululeko#87]
when i do a fresh install 
"pip install nkululeko"
lots of cuda stuff gets installed in dependence of torch, although most of the times the machine is without gps (mostly laptops)
but when there is a gpu, of course torch with gpu support should be installed.

**Comment by bagustris** [comment]
This is similar and may be a duplication of #33.

Usually, I installed torch manually since it depends on the cuda version and other torch family (torchaudio and torchvision). The easiest workaround is to leave Torch from `requirements.txt` and add additional instructions to Install Torch based on the user's computational resources (CPU or GPU).

**Comment by felixbur** [comment]
ok, i guess we use this as a solution: i remove torch from the setup.cfg and write somewhere some examples which one to install
